dist: trusty
sudo: false
language: node_js
node_js:
  - '10'
addons:
  chrome: stable
cache:
  directories:
    - "./node_modules"
install:
  - npm install
script:
  - npm run test -- --no-watch --no-progress --browsers=ChromeHeadless
notifications:
  slack:
    secure: JnpsQ0qKtP4NeNOaslhz57CLEyTPRhAdNoy6xRwD0i0vWYWUDAlYtx9PUoW1NIA23TIgjLKTGOPjlhRpKt/eyrh9oSUThSFl/+zNjfcdw2Bzx4WqAMlhgLPZokSDpzWTHpeGznMASCLH88myAAtewhLHxH/ZdZ3ntCLRbG7bf6vmxE95256q9+pcX1B4S9L+/D1HZp2b2KgjV7Yr9bcnEf65GQ4y9f6ZZIyA0dc/RhnmgIhd2AoOwNFgZYeTwutfVXGxJ79bmX4sqPrx+TvkrlsvrsUdJWT6XihjObnKRpDvuuiKwaVKK873h1FR2bCwvjx9Nz+XuPqQSXpkVrNgEPhj+u42/NOgg9fnsFrk6Dvw93+yMaRRwuw3kE6eD0puRiczsQM4R2QB/zjmYpVMg5Us2GpVU3r6WIfI+RRThrTWymwq9z3u94zqL6Ek/jHQ9EmBjY0hwdEDNTWHT7Dg4uBZ8BOeuzuCkuGK7qqmKbC6ChtRVJVyp+ZQtRamaHuLWuwtGsVSUg55YuSE4hknHS4uUwePFFwR+pYraoYM4AyIkMmdB1go659v7rGB8WI7zWoc0XybywaSE97nDfIMgW7kaTSSwINsHEIN4D5+9Av1WKSqA+Ma/Tp/NxSdRiM4dthMJ2kYEcXCfHyg99vZQ4Xb0MlAo3mcVVaFDvpthok=
